// mocks/dettaglioDocEmesso.mock.ts

export const mockDettaglioDocEmesso = (tipologiaFattura: string) => ({
    "idTestata": "6458",
    "idEnte": "234c45ca-da5f-4067-a4d6-1391774162b4",
    "ragioneSociale": "Comune di Bisceglie",
    "dataDocumento": "05/31/2024 00:00:00",
    "idDocumento": null,
    "totaleFattura": 7.61,
    "cup": null,
    "idContratto": "28e1103f-43c7-4268-bab3-91ee62cea226",
    "tipologiaFattura": tipologiaFattura, 
    "anno": "2024",
    "mese": "2",
    "totaleAnalogico": 7.61,
    "totaleDigitale": 0,
    "totaleNotificheAnalogiche": 1,
    "totaleNotificheDigitali": 0,
    "totale": 1,
    "datiFatturazione": null,
    "iva": 22,
    "totaleAnalogicoIva": 9.28,
    "totaleDigitaleIva": 0,
    "totaleIva": 9.2842,
    "firmata": null,
    "caricata": 0,
    "tipologiaContratto": "PAL",
    "anticipoDigitale": 0,
    "anticipoAnalogico": 0,
    "accontoDigitale": 0,
    "accontoAnalogico": 0,
    "stornoDigitale": 0,
    "stornoAnalogico": 0,
    "totaleStorni": null,
    "fattureSospese": []
});