// mocks/dettaglioDocEmesso.mock.ts

export const mockDettaglioDocEmesso = (tipologiaFattura: string) => ({
    "idTestata": "6458",
    "idEnte": "234c45ca-da5f-4067-a4d6-1391774162b4",
    "ragioneSociale": "Comune di Bisceglie",
    "dataDocumento": "05/31/2024 00:00:00",
    "idDocumento": null,
    "totaleFattura": 7.61,
    "cup": null,
    "idContratto": "28e1103f-43c7-4268-bab3-91ee62cea226",
    "tipologiaFattura": tipologiaFattura, 
    "anno": "2024",
    "mese": "2",
    "totaleAnalogico": 7.61,
    "totaleDigitale": 0,
    "totaleNotificheAnalogiche": 1,
    "totaleNotificheDigitali": 0,
    "totale": 1,
    "datiFatturazione": null,
    "iva": 22,
    "totaleAnalogicoIva": 9.28,
    "totaleDigitaleIva": 0,
    "totaleIva": 9.2842,
    "firmata": null,
    "caricata": 0,
    "tipologiaContratto": "PAL",
    "anticipoDigitale": 0,
    "anticipoAnalogico": 0,
    "accontoDigitale": 0,
    "accontoAnalogico": 0,
    "stornoDigitale": 0,
    "stornoAnalogico": 0,
    "totaleStorni": null,
    "fattureSospese": []
});

export const labelsAnticipo = [
    "Soggetto Aderente",
    "Tipologia Fattura",
    "Anno",
    "Mese",
    "Tipo Contratto",
    "ID Documento",
    "Cup",
    "Iva",
    "N. Notifiche Analogiche",
    "N. Notifiche Digitali",
    "N. Totale Notifiche",
    "Anticipo Analogico",
    "Anticipo Digitale",
    "Totale Imponibile",
];

export const labelsAcconto = [
    "Soggetto Aderente",
    "Tipologia Fattura",
    "Anno",
    "Mese",
    "Tipo Contratto",
    "ID Documento",
    "Cup",
    "Iva",
    "N. Notifiche Analogiche",
    "N. Notifiche Digitali",
    "N. Totale Notifiche",
    "Totale Imponibile Analogico",
    "Totale Imponibile Digitale",
    "Acconto Analogico",
    "Acconto Digitale",
    "Totale Imponibile",
];

export const labelsPrimoSaldo = [
    "Soggetto Aderente",
    "Tipologia Fattura",
    "Anno",
    "Mese",
    "Tipo Contratto",
    "ID Documento",
    "Cup",
    "Iva",
    "N. Notifiche Analogiche",
    "N. Notifiche Digitali",
    "N. Totale Notifiche",
    "Totale Imponibile Analogico",
    "Totale Imponibile Digitale",
    "Totale Imponibile",
]

export const labelsSecondoSaldo = [
    "Soggetto Aderente",
    "Tipologia Fattura",
    "Anno",
    "Mese",
    "Tipo Contratto",
    "ID Documento",
    "Cup",
    "Iva",
    "N. Notifiche Analogiche",
    "N. Notifiche Digitali",
    "N. Totale Notifiche",
    "Totale Imponibile Analogico",
    "Totale Imponibile Digitale",
    "Totale Imponibile",
];

export let labelsVarSemestrale = [
    "Soggetto Aderente",
    "Tipologia Fattura",
    "Anno",
    "Mese",
    "Tipo Contratto",
    "ID Documento",
    "Cup",
    "Iva",
    "N. Notifiche Analogiche",
    "N. Notifiche Digitali",
    "N. Totale Notifiche",
    "Totale Imponibile Analogico",
    "Totale Imponibile Digitale",
    "Totale Imponibile",
]